### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kjell-virus-maker** [TheEinzzCookie/Discord-Application-Raider#2]
Keeps giving me an error error:%20Ignored%20the%20following%20versions%20that%20require%20a%20different%20python%20version%3A%200.1.0%20Requires-Python%20%3E=3.13;%200%0A%E2%80%A22.0%20Requires-Python%20%3E=3.13;%200.2.1%20Requires-Python%20%3E=3.13%0AERROR%3A%20Could%20not%20find%20a%20version%20that%20satisfies%20the%20requirement%20audioop-lts%20(from%20versions%3A%20none)%0AERROR%3A%20No%20matching%20distribution%20found%20for%20audioop-lts%0ATraceback%20(most%20recent%20call%20last)%3A%0AFile%20%22/home/container/main-py%22,%20line%201,%20in%20%3C%20module%3E%0Aimport%20discord%0AModuleNotFoundError:%20No%20module%20named%20%22discord'

**Comment by TheEinzzCookie** [comment]
Hey. 
Whats your Python version? Check using `python --version`
Whats your pip version? Check using `pip --version`
Did you install the requirements?

**Comment by kjell-virus-maker** [comment]
Hi i have Python 3.12 and Pip 24 or Smth idk

**Comment by TheEinzzCookie** [comment]
You need the latest Python version. And did you install the requirements?

**Comment by kjell-virus-maker** [comment]
Windows 11 and now it doesnt work it only works on Replit (pls make js Version js is better anyway)

**Comment by TheEinzzCookie** [comment]
@kjell-virus-maker I will make a .js version maybe soon. But first tell me what exactly "doesnt work". Maybe provide screenshots, videos or tell me what exactly you did.

**Comment by TheEinzzCookie** [comment]
Closed due to inactivity. Please create a new issue if this error occurs again.
